// <auto-generated />
namespace CommercialAutomation.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_password : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_password));
        
        string IMigrationMetadata.Id
        {
            get { return "202107301647428_mig_password"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
