// <auto-generated />
namespace CommercialAutomation.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_EmployeeAbout : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_EmployeeAbout));
        
        string IMigrationMetadata.Id
        {
            get { return "202107291708155_mig_EmployeeAbout"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
